# Generated by Django 3.0.3 on 2020-03-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asas',
            options={'ordering': ['image']},
        ),
        migrations.AlterField(
            model_name='asas',
            name='image',
            field=models.ImageField(default=True, upload_to='pro'),
        ),
    ]
