# Generated by Django 3.0.3 on 2020-03-30 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asas', '0003_auto_20200329_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asas',
            old_name='users',
            new_name='user',
        ),
    ]
