# Generated by Django 3.0.3 on 2020-03-31 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asas', '0006_asas_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commint',
            options={'ordering': ['commint']},
        ),
    ]
