# Generated by Django 3.0.3 on 2020-04-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asas', '0007_auto_20200331_1948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commint',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='commint',
            name='post',
        ),
        migrations.AddField(
            model_name='commint',
            name='post',
            field=models.ManyToManyField(related_name='commint', to='asas.Asas'),
        ),
    ]
