# Generated by Django 3.0.3 on 2020-04-01 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asas', '0008_auto_20200401_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commint',
            name='post',
        ),
        migrations.AddField(
            model_name='commint',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='commint', to='asas.Asas'),
            preserve_default=False,
        ),
    ]
