# Generated by Django 3.0.3 on 2020-04-01 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asas', '0009_auto_20200401_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asas',
            name='slug',
        ),
    ]
