# Generated by Django 3.0.3 on 2020-04-01 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asas', '0010_remove_asas_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commint',
            old_name='post',
            new_name='post_id',
        ),
        migrations.RenameField(
            model_name='commint',
            old_name='user',
            new_name='user_id',
        ),
    ]
