# Generated by Django 3.0.3 on 2020-04-12 12:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asas', '0015_like_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like_post',
            name='current_post',
            field=models.ManyToManyField(null=True, related_name='mysate', to='asas.Asas'),
        ),
        migrations.AlterField(
            model_name='like_post',
            name='post',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
