# Generated by Django 3.0.3 on 2020-04-12 13:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asas', '0018_auto_20200412_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='asas',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
