# Generated by Django 3.0.3 on 2020-04-12 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asas', '0019_asas_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asas',
            name='likes',
        ),
        migrations.AlterField(
            model_name='like_post',
            name='current_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mysate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like_post',
            name='post',
            field=models.ManyToManyField(to='asas.Asas'),
        ),
    ]
