# Generated by Django 3.0.3 on 2020-04-13 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asas', '0021_auto_20200412_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asas',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='like_post',
            name='post',
        ),
        migrations.AddField(
            model_name='like_post',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asas.Asas'),
        ),
    ]
