# Generated by Django 3.0.3 on 2020-04-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asas', '0022_auto_20200413_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like_post',
            name='post',
        ),
        migrations.AddField(
            model_name='like_post',
            name='post',
            field=models.ManyToManyField(to='asas.Asas'),
        ),
    ]
