# Generated by Django 3.0.3 on 2020-04-14 13:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asas', '0024_asas_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asas',
            name='likes',
        ),
        migrations.AddField(
            model_name='asas',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
