# Generated by Django 3.0.3 on 2020-04-21 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asas', '0025_auto_20200414_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='asas',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asas.Asas'),
        ),
        migrations.AlterField(
            model_name='asas',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
