# Generated by Django 3.0.3 on 2020-04-21 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asas', '0027_auto_20200421_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asas',
            name='parent',
        ),
        migrations.AddField(
            model_name='asas',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parant', to='asas.Asas'),
        ),
    ]
