# Generated by Django 3.0.3 on 2020-04-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asas', '0028_auto_20200421_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asas',
            name='parent',
        ),
        migrations.AddField(
            model_name='asas',
            name='parent',
            field=models.ManyToManyField(related_name='_asas_parent_+', to='asas.Asas'),
        ),
    ]
