# Generated by Django 3.0.3 on 2020-05-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asas', '0031_add_book_book_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.IntegerField(default=True),
        ),
    ]
