# Generated by Django 3.0.3 on 2020-02-16 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abook', '0002_contact_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='password',
        ),
    ]
