# Generated by Django 3.0.3 on 2020-02-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abook', '0004_contact_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='As',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, null='true')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=10)),
                ('zipcode', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
