# Generated by Django 3.0.3 on 2020-02-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abook', '0006_auto_20200223_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='data',
            field=models.DateField(null='true'),
            preserve_default='true',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(upload_to='fropile_image'),
        ),
    ]
