# Generated by Django 3.0.3 on 2020-02-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abook', '0007_auto_20200223_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='data',
            field=models.CharField(max_length=122, null='true'),
        ),
    ]
