# Generated by Django 3.0.3 on 2020-02-24 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abook', '0008_auto_20200223_2125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='data',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mobil_nu',
        ),
    ]
