# Generated by Django 3.0.3 on 2020-03-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abook', '0015_sher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
