# Generated by Django 3.0.3 on 2020-03-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abook', '0016_auto_20200312_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pro'),
        ),
    ]
