# Generated by Django 3.0.3 on 2020-03-12 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abook', '0017_auto_20200312_2047'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sher',
        ),
    ]
