# Generated by Django 3.0.3 on 2020-03-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abook', '0018_delete_sher'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=122, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='contry',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='mobil',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
