# Generated by Django 3.0.3 on 2020-03-20 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abook', '0019_auto_20200320_1029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['image', 'address', 'contry', 'mobil']},
        ),
    ]
