# Generated by Django 3.0.3 on 2020-03-26 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abook', '0020_auto_20200320_1041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['image']},
        ),
    ]
