# Generated by Django 3.0.3 on 2020-03-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abook', '0021_auto_20200326_2049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user']},
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=True, upload_to='pro'),
        ),
    ]
