# Generated by Django 3.0.3 on 2020-05-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asas', '0031_add_book_book_post'),
        ('abook', '0022_auto_20200327_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ebooks',
            field=models.ManyToManyField(blank=True, to='asas.Book'),
        ),
    ]
