# Generated by Django 3.0.3 on 2020-05-15 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abook', '0023_profile_ebooks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
    ]
