# Generated by Django 3.0.3 on 2020-05-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='descreption',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='porm',
            field=models.CharField(choices=[('Enterprise', 'ent'), ('Professional', 'pro'), ('Free', 'free')], max_length=30),
        ),
    ]
