# Generated by Django 3.0.3 on 2020-05-16 21:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0004_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='porm',
        ),
        migrations.AddField(
            model_name='video',
            name='porm',
            field=models.ManyToManyField(related_name='porm', to=settings.AUTH_USER_MODEL),
        ),
    ]
