# Generated by Django 3.0.3 on 2020-05-16 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_auto_20200517_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='current_user',
        ),
        migrations.AddField(
            model_name='friend',
            name='current_user',
            field=models.ManyToManyField(related_name='owners', to='video.Video'),
        ),
    ]
