# Generated by Django 3.0.3 on 2020-05-17 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0008_auto_20200517_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='current_user',
        ),
        migrations.AddField(
            model_name='friend',
            name='current_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='video.Video'),
            preserve_default=False,
        ),
    ]
