# Generated by Django 3.0.3 on 2020-05-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_auto_20200517_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='current_user',
        ),
        migrations.AddField(
            model_name='friend',
            name='current_user',
            field=models.ManyToManyField(related_name='owners', to='video.Video'),
        ),
    ]
